dist: xenial
language: python
python:
  - "3.6"
addons:
  apt:
    packages:
    - python3-dbus # Make sure that all system deps for dbus are installed
    - libdbus-1-dev # Make sure that all system deps for dbus are installed
    - libdbus-glib-1-dev # Make sure that all system deps for dbus are installed

install:
  - pip3 install -r requirements.txt --no-deps
  - pip3 install black 
  - pip install coveralls 

script: 
  - coverage run --source pifi setup.py test
  - black --check pifi

after_success:
    coveralls
